debug: false

#---------------#
#
#---------------#


#----------------#
# Disable Worlds #
#----------------#

disabled-worlds:
  - 'world_nether'

#----------#
# Movement #
#----------#

launchpad:
  enabled: true
  type: "SLIME_BLOCK"
  power: 2
  power_y: 2
  # INTEGERS ONLY
  cooldown: 2

double_jump:
  enabled: true
  power: 1.5
  power_y: 0.5
  # INTEGERS ONLY
  cooldown: 2


#-------#
# ITEMS #
#-------#
playervisibility:
  enabled: true
  visible_text: '&rPlayers: &aVisible'
  hidden_text: '&rPlayers: &cHidden'

shop:
  enabled: true
  command: "buy"
  item:
    name: "&aShop"
    type: "EMERALD"

socials:
  enabled: true
  size: 27
  title: "Socials"
  item:
    type: "PLAYER_HEAD"
    value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzU1ZTJkYzQ2Mzk5YjdiOTI3NTIyMWZjZGM4N2M2NmU1OGQwZDMwNDRkY2Y2MmFmMDQ2NTEyMmMxY2Q3ZTBiYyJ9fX0=" # Leave empty if item isnt SKULL
    name: "&6Socials"
  items:
    tiktok: # Key for this item
      slot: 13 # Slot for this item (0-based index)
      material: PLAYER_HEAD  # Material for the item
      name: "&dTik&bTok"  # Display name of the item with placeholder
      lore: # Lore for the item/
      value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmNmMjEwNWJiNzM3NjM4ODMzMDMzZGQ4MjQ0MDcxZTc1ODcwZTJlMTFjMjYxN2U1NDJlODkyNGZiMmI5MDE4MCJ9fX0="
      message: "tiktok.com"
    youtube: # Key for this item
      slot: 15 # Slot for this item (0-based index)
      material: PLAYER_HEAD  # Material for the item
      name: "&cYoutube"  # Display name of the item with placeholder
      lore: # Lore for the item
      value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWM1NmRkYmVmMWI4MWJkNTdjOWIxYzZkNWQxYjc4YjU0NzM3YjcxOTkyOWIyOWMyYTkzMGE1ZjdjMmFlNGE4NiJ9fX0="
      message: "youtube.com"

  fill:
    name: " "
    type: "BLACK_STAINED_GLASS_PANE"
item_on_join:
  enabled: true
  forceinventory: true
  features:
    compass:
      enabled: true
      slot: 5
    shop:
      enabled: true
      slot: 9
    socials:
      enabled: true
      slot: 1
    playervisibility:
      enabled: true
      slot: 8


close_button:
  slot: 23
  material: "BARRIER"
  name: "&aClose"

#---------------#
# Teleportation #
#---------------#

antivoid:
  enabled: true

spawn:
  world: "world"
  x: 0
  y: 200
  z: 0
  #YAW AND PITCH WILL ROUND TO {-135, -90, -45, 0, 45, 90, 135}, YOU CAN MANUALLY OVERRIDE THIS HERE
  yaw: 0
  pitch: 0


#-----------------#
# PLAYER SETTINGS #
#-----------------#

player:
  spawn_on_join: true
  fly:
    enabled: true
    default: true
  join_message:
    enabled: true
    message: "%name% joined"
  leave_message:
    enabled: true
    message: "%name% left"
  join_firework:
    enabled: true
    type: "BALL"
    #POWER 1-3
    power: 1
  bossbar:
    enabled: true
    color: "PURPLE"
    # ANIMATIONS IN TICKS
    animation:
      change-interval: 10
      texts:
        - "&6&lW_"
        - "&6&lW_"
        - "&6&lWe_"
        - "&6&lWel_"
        - "&6&lWelc_"
        - "&6&lWelco_"
        - "&6&lWelcom_"
        - "&6&lWelcome_"
        - "&6&lWelcome_"
        - "&6&lWelcome_"
        - "&6&lWelcome_"
        - "&6&lWelcom_"
        - "&6&lWelco_"
        - "&6&lWelc_"
        - "&6&lWel_"
        - "&6&lWe_"
        - "&6&lW_"
        - "&6&lW_"

actions_on_join:
  - '[TITLE] &aHubbly;configure me;20;70;20'
  - '[SOUND] block.note_block.chime'
  - '[FIREWORK] BALL;255;0;255;2'

#---------------------#
# WORLD EVENT MANAGER #
#---------------------#

cancel_events:
  block_place: true
  block_break: true
  damage: true
  weather: true
  item_drop: true
  item_pickup: true
  hunger: true
  mob_spawn: true
  block_burn: true
  death_messages: true
  leaf_decay: true

#----------#
# MESSAGES #
#----------#

messages:
  no_console: "Only players can use this command!"
  no_permission_command: "You do not have permission to use this command!"
  no_permission_use: "You do not have permission to use this!"
  reload: "Reloaded Hubbly plugin"
  fly:
    enable: "Flight mode enabled."
    disable: "Flight mode disabled."

